<script setup>
import { Head, Link } from '@inertiajs/vue3';

defineProps({
    canLogin: Boolean,
    canRegister: Boolean,
    laravelVersion: String,
    phpVersion: String,
});
</script>

<template>
    <Head title="Welcome" />

    <div class="relative sm:flex sm:justify-center sm:items-center min-h-screen   selection:text-white color-change-2x">


        <div class="max-w-7xl mx-auto p-6 lg:p-8">
            <div class="flex justify-center mt-16 px-6 sm:items-center sm:justify-between">
                <div class="text-center text-sm text-gray-500  sm:text-left">
                    <div class="flex items-center gap-4">
                        <div v-if="canLogin" class="">

                            <section class="bg-transparent ">
                                <div class="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16 z-10 relative">
                                    <img class="w-72 mx-auto" src="../../image/logo_main.png">
                                    <h1
                                        class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl ">
                                        Hardware City</h1>
                                    <p class="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 lg:px-48 ">
                                        We offer the best selection of high-quality tools at affordable prices. From power
                                        tools to hand tools, we have everything you need for your projects. Our
                                        knowledgeable staff is here to assist you in finding the right tool, and we also
                                        offer repair and maintenance services. Visit us today for all your hardware needs!
                                    </p>
                                    <a type="button" :href="route('login')"
                                        class="text-gray-900 bg-[#F7BE38] hover:bg-[#F7BE38]/90 focus:ring-4 focus:outline-none focus:ring-[#F7BE38]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center mr-2 mb-2">
                                        Log in
                                    </a>
                                </div>
                                <div class="bg-gradient-to-b from-blue-50 to-transparent ">
                                </div>
                            </section>

                            <!-- <a type="button" :href="route('login')"
                                class="text-gray-900 bg-[#F7BE38] hover:bg-[#F7BE38]/90 focus:ring-4 focus:outline-none focus:ring-[#F7BE38]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center mr-2 mb-2">
                                Log in
                        </a> -->
                            <!-- <Link v-if="$page.props.auth.user" :href="route('dashboard')"
                                class="font-semibold text-gray-600 hover:text-gray-900  focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500">
                            Dashboard</Link> -->

                            <!-- <template v-else>
                                <Link :href="route('login')"
                                    class="font-semibold text-gray-600 hover:text-gray-900  focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500">
                                Log in</Link>

                                <Link v-if="canRegister" :href="route('register')"
                                    class="ml-4 font-semibold text-gray-600 hover:text-gray-900  focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500">
                                Register</Link>
                            </template> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<style >
.color-change-2x {
    -webkit-animation: color-change-2x 2s linear infinite alternate both;
    animation: color-change-2x 2s linear infinite alternate both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-8-1 21:19:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation color-change-2x
 * ----------------------------------------
 */
@-webkit-keyframes color-change-2x {
    0% {
        background: white;
    }

    100% {
        background: #ffd82c36;
    }
}

@keyframes color-change-2x {
    0% {
        background: white;
    }

    100% {
        background: #ffd82c36;
    }
}
</style>
